#!/usr/bin/env bun
// @generated by mcporter@0.0.0. DO NOT EDIT.
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Command } from 'commander';
import { createGeneratedKeepAliveRuntime, createRuntime, createServerProxy, handleDaemonCli } from 'mcporter';
import { createCallResult } from 'mcporter';

const __mcpScriptDir = path.dirname(fileURLToPath(import.meta.url));
const __mcpRelativeStdioCwd: string | null = null;
const embeddedServer = {
  "command": {
    "args": [
      "-y",
      "@21st-dev/magic@latest"
    ],
    "command": "npx",
    "cwd": "D:\\uwuwu_agent",
    "kind": "stdio"
  },
  "description": "21st-magic",
  "name": "util_magic_ui_chat"
} as const;
const embeddedSchemas = {
  "21st_magic_component_builder": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
      "absolutePathToCurrentFile": {
        "description": "Absolute path to the current file to which we want to apply changes",
        "type": "string"
      },
      "absolutePathToProjectDirectory": {
        "description": "Absolute path to the project root directory",
        "type": "string"
      },
      "message": {
        "description": "Full users message",
        "type": "string"
      },
      "searchQuery": {
        "description": "Generate a search query for 21st.dev (library for searching UI components) to find a UI component that matches the user's message. Must be a two-four words max or phrase",
        "type": "string"
      },
      "standaloneRequestQuery": {
        "description": "You need to formulate what component user wants to create, based on his message, possbile chat histroy and a place where he makes the request.Extract additional context about what should be done to create a ui component/page based on the user's message, search query, and conversation history, files. Don't halucinate and be on point.",
        "type": "string"
      }
    },
    "required": [
      "message",
      "searchQuery",
      "absolutePathToCurrentFile",
      "absolutePathToProjectDirectory",
      "standaloneRequestQuery"
    ],
    "type": "object"
  },
  "21st_magic_component_inspiration": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
      "message": {
        "description": "Full users message",
        "type": "string"
      },
      "searchQuery": {
        "description": "Search query for 21st.dev (library for searching UI components) to find a UI component that matches the user's message. Must be a two-four words max or phrase",
        "type": "string"
      }
    },
    "required": [
      "message",
      "searchQuery"
    ],
    "type": "object"
  },
  "21st_magic_component_refiner": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
      "absolutePathToRefiningFile": {
        "description": "Absolute path to the file that needs to be refined",
        "type": "string"
      },
      "context": {
        "description": "Extract the specific UI elements and aspects that need improvement based on user messages, code, and conversation history. Identify exactly which components (buttons, forms, modals, etc.) the user is referring to and what aspects (styling, layout, responsiveness, etc.) they want to enhance. Do not include generic improvements - focus only on what the user explicitly mentions or what can be reasonably inferred from the available context. If nothing specific is mentioned or you cannot determine what needs improvement, return an empty string.",
        "type": "string"
      },
      "userMessage": {
        "description": "Full user's message about UI refinement",
        "type": "string"
      }
    },
    "required": [
      "userMessage",
      "absolutePathToRefiningFile",
      "context"
    ],
    "type": "object"
  },
  "logo_search": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
      "format": {
        "description": "Output format",
        "enum": [
          "JSX",
          "TSX",
          "SVG"
        ],
        "type": "string"
      },
      "queries": {
        "description": "List of company names to search for logos",
        "items": {
          "type": "string"
        },
        "type": "array"
      }
    },
    "required": [
      "queries",
      "format"
    ],
    "type": "object"
  }
} as const;
const embeddedName = "util_magic_ui_chat";
const embeddedDescription = "21st-magic";
const generatorInfo = "Generated by mcporter@0.0.0 — https://github.com/openclaw/mcporter";
const generatorTools = [
  {
    "description": "\n\"Use this tool when the user requests a new UI component—e.g., mentions /ui, /21 /21st, or asks for a button, input, dialog, table, form, banner, card, or other React component.\nThis tool ONLY returns the text snippet for that UI component. \nAfter calling this tool, you must edit or add files to integrate the snippet into the codebase.\"\n",
    "flags": "--message <message> --search-query <search-query> --absolute-path-to-current-file <absolute-path-to-current-file> --absolute-path-to-project-directory <absolute-path-to-project-directory> --standalone-request-query <standalone-request-query> [--raw <json>]",
    "name": "21st-magic-component-builder",
    "usage": "21st-magic-component-builder --message <message> --search-query <search-query> --absolute-path-to-current-file <absolute-path-to-current-file> --absolute-path-to-project-directory <absolute-path-to-project-directory> --standalone-request-query <standalone-request-query> [--raw <json>]"
  },
  {
    "description": "\n\"Use this tool when the user wants to see component, get inspiration, or /21st fetch data and previews from 21st.dev. This tool returns the JSON data of matching components without generating new code. This tool ONLY returns the text snippet for that UI component. \nAfter calling this tool, you must edit or add files to integrate the snippet into the codebase.\"\n",
    "flags": "--message <message> --search-query <search-query> [--raw <json>]",
    "name": "21st-magic-component-inspiration",
    "usage": "21st-magic-component-inspiration --message <message> --search-query <search-query> [--raw <json>]"
  },
  {
    "description": "\n\"Use this tool when the user requests to re-design/refine/improve current UI component with /ui or /21 commands, \nor when context is about improving, or refining UI for a React component or molecule (NOT for big pages).\nThis tool improves UI of components and returns redesigned version of the component and instructions on how to implement it.\"\n",
    "flags": "--user-message <user-message> --absolute-path-to-refining-file <absolute-path-to-refining-file> --context <context> [--raw <json>]",
    "name": "21st-magic-component-refiner",
    "usage": "21st-magic-component-refiner --user-message <user-message> --absolute-path-to-refining-file <absolute-path-to-refining-file> --context <context> [--raw <json>]"
  },
  {
    "description": "\nSearch and return logos in specified format (JSX, TSX, SVG).\nSupports single and multiple logo searches with category filtering.\nCan return logos in different themes (light/dark) if available.\n\nWhen to use this tool:\n1. When user types \"/logo\" command (e.g., \"/logo GitHub\")\n2. When user asks to add a company logo that's not in the local project\n\nExample queries:\n- Single company: [\"discord\"]\n- Multiple companies: [\"discord\", \"github\", \"slack\"]\n- Specific brand: [\"microsoft office\"]\n- Command style: \"/logo GitHub\" -> [\"github\"]\n- Request style: \"Add Discord logo to the project\" -> [\"discord\"]\n\nFormat options:\n- TSX: Returns TypeScript React component\n- JSX: Returns JavaScript React component\n- SVG: Returns raw SVG markup\n\nEach result includes:\n- Component name (e.g., DiscordIcon)\n- Component code\n- Import instructions\n",
    "flags": "--queries <queries:value1,value2> --format <format:JSX|TSX|SVG> [--raw <json>]",
    "name": "logo-search",
    "usage": "logo-search --queries <queries:value1,value2> --format <format:JSX|TSX|SVG> [--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "artifact": {
    "kind": "template",
    "path": ""
  },
  "generatedAt": "1970-01-01T00:00:00.000Z",
  "generator": {
    "name": "mcporter",
    "version": "0.0.0"
  },
  "invocation": {
    "bundler": "bun",
    "minify": false,
    "runtime": "bun",
    "serverRef": "{\"command\":{\"args\":[\"-y\",\"@21st-dev/magic@latest\"],\"command\":\"npx\",\"cwd\":\"D:\\\\uwuwu_agent\",\"kind\":\"stdio\"},\"description\":\"21st-magic\",\"name\":\"util_magic_ui_chat\"}",
    "timeoutMs": 30000
  },
  "schemaVersion": 1,
  "server": {
    "definition": {
      "command": {
        "args": [
          "-y",
          "@21st-dev/magic@latest"
        ],
        "command": "npx",
        "cwd": "D:\\uwuwu_agent",
        "kind": "stdio"
      },
      "description": "21st-magic",
      "name": "util_magic_ui_chat"
    },
    "name": "util_magic_ui_chat"
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 30000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "21st-magic-component-builder": "function 21st_magic_component_builder(message: string, searchQuery: string, absolutePathToCurrentFile: string, absolutePathToProjectDirectory: string, standaloneRequestQuery: string);",
  "21st-magic-component-inspiration": "function 21st_magic_component_inspiration(message: string, searchQuery: string);",
  "21st-magic-component-refiner": "function 21st_magic_component_refiner(userMessage: string, absolutePathToRefiningFile: string, context: string);",
  "logo-search": "function logo_search(queries: string[], format: \"JSX\" | \"TSX\" | \"SVG\");"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("21st-magic-component-builder")
	.summary("21st-magic-component-builder --message <message> --search-query <search-query> --absolute-path-to-current-file <absolute-path-to-current-file> --absolute-path-to-project-directory <absolute-path-to-project-directory> --standalone-request-query <standalone-request-query> [--raw <json>]")
	.description("\n\"Use this tool when the user requests a new UI component—e.g., mentions /ui, /21 /21st, or asks for a button, input, dialog, table, form, banner, card, or other React component.\nThis tool ONLY returns the text snippet for that UI component. \nAfter calling this tool, you must edit or add files to integrate the snippet into the codebase.\"\n")
	.usage("--message <message> --search-query <search-query> --absolute-path-to-current-file <absolute-path-to-current-file> --absolute-path-to-project-directory <absolute-path-to-project-directory> --standalone-request-query <standalone-request-query> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--message <message>", "Full users message")
	.option("--search-query <search-query>", "Generate a search query for 21st.dev (library for searching UI components) to find a UI component that matches the user's message. Must be a two-four words max or phrase")
	.option("--absolute-path-to-current-file <absolute-path-to-current-file>", "Absolute path to the current file to which we want to apply changes (example: /path/to/file.md)")
	.option("--absolute-path-to-project-directory <absolute-path-to-project-directory>", "Absolute path to the project root directory (example: /path/to/file.md)")
	.option("--standalone-request-query <standalone-request-query>", "You need to formulate what component user wants to create, based on his message, possbile chat histroy and a place where he makes the request.Extract additional context about what should be done to create a ui component/page based on the user's message, search query, and conversation history, files. Don't halucinate and be on point.")
	
	.alias("21st_magic_component_builder")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtimeContext = await ensureRuntime();
		const runtime = runtimeContext.runtime;
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (!cmdOpts.raw) {
				const missingRequired = [{ value: cmdOpts.message, flag: "--message" }, { value: cmdOpts.searchQuery, flag: "--search-query" }, { value: cmdOpts.absolutePathToCurrentFile, flag: "--absolute-path-to-current-file" }, { value: cmdOpts.absolutePathToProjectDirectory, flag: "--absolute-path-to-project-directory" }, { value: cmdOpts.standaloneRequestQuery, flag: "--standalone-request-query" }].filter((entry) => entry.value === undefined).map((entry) => entry.flag);
			if (missingRequired.length > 0) {
				throw new Error('Missing required option' + (missingRequired.length === 1 ? '' : 's') + ': ' + missingRequired.join(', '));
			}
				if (cmdOpts.message !== undefined) args.message = cmdOpts.message;
		if (cmdOpts.searchQuery !== undefined) args.searchQuery = cmdOpts.searchQuery;
		if (cmdOpts.absolutePathToCurrentFile !== undefined) args.absolutePathToCurrentFile = cmdOpts.absolutePathToCurrentFile;
		if (cmdOpts.absolutePathToProjectDirectory !== undefined) args.absolutePathToProjectDirectory = cmdOpts.absolutePathToProjectDirectory;
		if (cmdOpts.standaloneRequestQuery !== undefined) args.standaloneRequestQuery = cmdOpts.standaloneRequestQuery;
			}
			const call = (proxy.21stMagicComponentBuilder as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtimeContext.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call util_magic_ui_chat.21st_magic_component_builder(message: \"va, ...)");

program
	.command("21st-magic-component-inspiration")
	.summary("21st-magic-component-inspiration --message <message> --search-query <search-query> [--raw <json>]")
	.description("\n\"Use this tool when the user wants to see component, get inspiration, or /21st fetch data and previews from 21st.dev. This tool returns the JSON data of matching components without generating new code. This tool ONLY returns the text snippet for that UI component. \nAfter calling this tool, you must edit or add files to integrate the snippet into the codebase.\"\n")
	.usage("--message <message> --search-query <search-query> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--message <message>", "Full users message")
	.option("--search-query <search-query>", "Search query for 21st.dev (library for searching UI components) to find a UI component that matches the user's message. Must be a two-four words max or phrase")
	
	.alias("21st_magic_component_inspiration")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtimeContext = await ensureRuntime();
		const runtime = runtimeContext.runtime;
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (!cmdOpts.raw) {
				const missingRequired = [{ value: cmdOpts.message, flag: "--message" }, { value: cmdOpts.searchQuery, flag: "--search-query" }].filter((entry) => entry.value === undefined).map((entry) => entry.flag);
			if (missingRequired.length > 0) {
				throw new Error('Missing required option' + (missingRequired.length === 1 ? '' : 's') + ': ' + missingRequired.join(', '));
			}
				if (cmdOpts.message !== undefined) args.message = cmdOpts.message;
		if (cmdOpts.searchQuery !== undefined) args.searchQuery = cmdOpts.searchQuery;
			}
			const call = (proxy.21stMagicComponentInspiration as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtimeContext.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call util_magic_ui_chat.21st_magic_component_inspiration(message:, ...)");

program
	.command("21st-magic-component-refiner")
	.summary("21st-magic-component-refiner --user-message <user-message> --absolute-path-to-refining-file <absolute-path-to-refining-file> --context <context> [--raw <json>]")
	.description("\n\"Use this tool when the user requests to re-design/refine/improve current UI component with /ui or /21 commands, \nor when context is about improving, or refining UI for a React component or molecule (NOT for big pages).\nThis tool improves UI of components and returns redesigned version of the component and instructions on how to implement it.\"\n")
	.usage("--user-message <user-message> --absolute-path-to-refining-file <absolute-path-to-refining-file> --context <context> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--user-message <user-message>", "Full user's message about UI refinement")
	.option("--absolute-path-to-refining-file <absolute-path-to-refining-file>", "Absolute path to the file that needs to be refined (example: /path/to/file.md)")
	.option("--context <context>", "Extract the specific UI elements and aspects that need improvement based on user messages, code, and conversation history. Identify exactly which components (buttons, forms, modals, etc.) the user is referring to and what aspects (styling, layout, responsiveness, etc.) they want to enhance. Do not include generic improvements - focus only on what the user explicitly mentions or what can be reasonably inferred from the available context. If nothing specific is mentioned or you cannot determine what needs improvement, return an empty string.")
	
	.alias("21st_magic_component_refiner")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtimeContext = await ensureRuntime();
		const runtime = runtimeContext.runtime;
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (!cmdOpts.raw) {
				const missingRequired = [{ value: cmdOpts.userMessage, flag: "--user-message" }, { value: cmdOpts.absolutePathToRefiningFile, flag: "--absolute-path-to-refining-file" }, { value: cmdOpts.context, flag: "--context" }].filter((entry) => entry.value === undefined).map((entry) => entry.flag);
			if (missingRequired.length > 0) {
				throw new Error('Missing required option' + (missingRequired.length === 1 ? '' : 's') + ': ' + missingRequired.join(', '));
			}
				if (cmdOpts.userMessage !== undefined) args.userMessage = cmdOpts.userMessage;
		if (cmdOpts.absolutePathToRefiningFile !== undefined) args.absolutePathToRefiningFile = cmdOpts.absolutePathToRefiningFile;
		if (cmdOpts.context !== undefined) args.context = cmdOpts.context;
			}
			const call = (proxy.21stMagicComponentRefiner as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtimeContext.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call util_magic_ui_chat.21st_magic_component_refiner(userMessage:, ...)");

program
	.command("logo-search")
	.summary("logo-search --queries <queries:value1,value2> --format <format:JSX|TSX|SVG> [--raw <json>]")
	.description("\nSearch and return logos in specified format (JSX, TSX, SVG).\nSupports single and multiple logo searches with category filtering.\nCan return logos in different themes (light/dark) if available.\n\nWhen to use this tool:\n1. When user types \"/logo\" command (e.g., \"/logo GitHub\")\n2. When user asks to add a company logo that's not in the local project\n\nExample queries:\n- Single company: [\"discord\"]\n- Multiple companies: [\"discord\", \"github\", \"slack\"]\n- Specific brand: [\"microsoft office\"]\n- Command style: \"/logo GitHub\" -> [\"github\"]\n- Request style: \"Add Discord logo to the project\" -> [\"discord\"]\n\nFormat options:\n- TSX: Returns TypeScript React component\n- JSX: Returns JavaScript React component\n- SVG: Returns raw SVG markup\n\nEach result includes:\n- Component name (e.g., DiscordIcon)\n- Component code\n- Import instructions\n")
	.usage("--queries <queries:value1,value2> --format <format:JSX|TSX|SVG> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--queries <queries:value1,value2>", "List of company names to search for logos (example: value1,value2)", (value) => parseArrayOption(value, 'string'))
	.option("--format <format:JSX|TSX|SVG>", "Output format (choices: JSX, TSX, SVG; example: JSX)")
	
	.alias("logo_search")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtimeContext = await ensureRuntime();
		const runtime = runtimeContext.runtime;
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (!cmdOpts.raw) {
				const missingRequired = [{ value: cmdOpts.queries, flag: "--queries" }, { value: cmdOpts.format, flag: "--format" }].filter((entry) => entry.value === undefined).map((entry) => entry.flag);
			if (missingRequired.length > 0) {
				throw new Error('Missing required option' + (missingRequired.length === 1 ? '' : 's') + ': ' + missingRequired.join(', '));
			}
				if (cmdOpts.queries !== undefined) args.queries = cmdOpts.queries;
		if (cmdOpts.format !== undefined) args.format = cmdOpts.format;
			}
			const call = (proxy.logoSearch as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtimeContext.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call util_magic_ui_chat.logo_search(queries: [\"value1\", \"value2\"], ...)");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n') + '\n';
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}


function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	const rawPayload = unwrapRawPayload(wrapped.raw);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json !== null) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			console.log(JSON.stringify(rawPayload, null, 2));
			return;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(rawPayload, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(rawPayload, null, 2));
	}
}

function unwrapRawPayload(value: unknown): unknown {
	if (value && typeof value === 'object' && 'raw' in value) {
		return (value as { raw: unknown }).raw;
	}
	return value;
}

function parseArrayOption(value: string, itemType: 'string' | 'number' | 'boolean' | 'json') {
	const trimmed = value.trim();
	if (trimmed.startsWith('[')) {
		const parsed = JSON.parse(trimmed);
		if (!Array.isArray(parsed)) {
			throw new Error('Expected a JSON array.');
		}
		return parsed;
	}
	if (itemType === 'json') {
		const parsed = JSON.parse('[' + value + ']');
		if (!Array.isArray(parsed)) {
			throw new Error('Expected JSON array items.');
		}
		return parsed;
	}
	const values = value.split(',').map((entry) => entry.trim());
	if (itemType === 'number') {
		return values.map((entry) => parseFloat(entry));
	}
	if (itemType === 'boolean') {
		return values.map((entry) => entry !== 'false');
	}
	return values;
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		const stdio = server.command as Record<string, unknown>;
		const resolvedCwd =
			__mcpRelativeStdioCwd !== null
				? path.resolve(__mcpScriptDir, __mcpRelativeStdioCwd)
				: typeof stdio.cwd === 'string' && stdio.cwd.length > 0
					? stdio.cwd
					: undefined;
		return {
			...base,
			command: {
				...stdio,
				args: [ ...((server.command as any).args ?? []) ],
				...(resolvedCwd !== undefined ? { cwd: resolvedCwd } : {}),
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js') || scriptPath.endsWith('.mjs') || scriptPath.endsWith('.cjs')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime() {
	const server = normalizeEmbeddedServer(embeddedServer);
	const baseRuntime = await createRuntime({
		servers: [server as any],
	});
	return await createGeneratedKeepAliveRuntime(baseRuntime, server as any);
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

function parseGeneratedDaemonInvocation(rawArgs: string[]): { args: string[]; configPath: string; rootDir?: string } | null {
	const args = [...rawArgs];
	let configPath: string | undefined;
	let rootDir: string | undefined;
	while (args.length > 0) {
		const token = args[0];
		if (token === '--config') {
			args.shift();
			configPath = args.shift();
			continue;
		}
		if (token?.startsWith('--config=')) {
			args.shift();
			configPath = token.slice('--config='.length);
			continue;
		}
		if (token === '--root') {
			args.shift();
			rootDir = args.shift();
			continue;
		}
		if (token?.startsWith('--root=')) {
			args.shift();
			rootDir = token.slice('--root='.length);
			continue;
		}
		break;
	}
	if (args[0] !== 'daemon') {
		return null;
	}
	if (!configPath) {
		throw new Error('Generated daemon invocation is missing --config.');
	}
	return { args: args.slice(1), configPath, rootDir };
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	const daemonInvocation = parseGeneratedDaemonInvocation(args);
	if (daemonInvocation) {
		await handleDaemonCli([...daemonInvocation.args], {
			configPath: daemonInvocation.configPath,
			configExplicit: true,
			rootDir: daemonInvocation.rootDir,
		});
		return;
	}
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
